//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.KandidatService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KandidatInfo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Server")]
    [System.SerializableAttribute()]
    public partial class KandidatInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jurusanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string misiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int nomorUrutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] pictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string visiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jurusan {
            get {
                return this.jurusanField;
            }
            set {
                if ((object.ReferenceEquals(this.jurusanField, value) != true)) {
                    this.jurusanField = value;
                    this.RaisePropertyChanged("jurusan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string misi {
            get {
                return this.misiField;
            }
            set {
                if ((object.ReferenceEquals(this.misiField, value) != true)) {
                    this.misiField = value;
                    this.RaisePropertyChanged("misi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nomorUrut {
            get {
                return this.nomorUrutField;
            }
            set {
                if ((this.nomorUrutField.Equals(value) != true)) {
                    this.nomorUrutField = value;
                    this.RaisePropertyChanged("nomorUrut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] picture {
            get {
                return this.pictureField;
            }
            set {
                if ((object.ReferenceEquals(this.pictureField, value) != true)) {
                    this.pictureField = value;
                    this.RaisePropertyChanged("picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodi {
            get {
                return this.prodiField;
            }
            set {
                if ((object.ReferenceEquals(this.prodiField, value) != true)) {
                    this.prodiField = value;
                    this.RaisePropertyChanged("prodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string visi {
            get {
                return this.visiField;
            }
            set {
                if ((object.ReferenceEquals(this.visiField, value) != true)) {
                    this.visiField = value;
                    this.RaisePropertyChanged("visi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KandidatService.IKandidat")]
    public interface IKandidat {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKandidat/ShowKandidat", ReplyAction="http://tempuri.org/IKandidat/ShowKandidatResponse")]
        Web_Client.KandidatService.KandidatInfo[] ShowKandidat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKandidat/ShowKandidat", ReplyAction="http://tempuri.org/IKandidat/ShowKandidatResponse")]
        System.Threading.Tasks.Task<Web_Client.KandidatService.KandidatInfo[]> ShowKandidatAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKandidatChannel : Web_Client.KandidatService.IKandidat, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KandidatClient : System.ServiceModel.ClientBase<Web_Client.KandidatService.IKandidat>, Web_Client.KandidatService.IKandidat {
        
        public KandidatClient() {
        }
        
        public KandidatClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KandidatClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KandidatClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KandidatClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Web_Client.KandidatService.KandidatInfo[] ShowKandidat() {
            return base.Channel.ShowKandidat();
        }
        
        public System.Threading.Tasks.Task<Web_Client.KandidatService.KandidatInfo[]> ShowKandidatAsync() {
            return base.Channel.ShowKandidatAsync();
        }
    }
}
