//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Client.MahasiswaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MahasiswaService.IMahasiswa")]
    public interface IMahasiswa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMahasiswa/login", ReplyAction="http://tempuri.org/IMahasiswa/loginResponse")]
        bool login(string ID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMahasiswa/login", ReplyAction="http://tempuri.org/IMahasiswa/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string ID, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMahasiswaChannel : Web_Client.MahasiswaService.IMahasiswa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MahasiswaClient : System.ServiceModel.ClientBase<Web_Client.MahasiswaService.IMahasiswa>, Web_Client.MahasiswaService.IMahasiswa {
        
        public MahasiswaClient() {
        }
        
        public MahasiswaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MahasiswaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MahasiswaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MahasiswaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string ID, string Password) {
            return base.Channel.login(ID, Password);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string ID, string Password) {
            return base.Channel.loginAsync(ID, Password);
        }
    }
}
